services:
  face-cluster:
    build:
      context: .
    image: face-cluster
    container_name: fc02
    volumes:
      - ./database:/app/database
      - ./encodings:/app/encodings
      - ./results:/app/results
    command: >
      sh -c "python /app/src/encode_faces.py &&
             python /app/src/cluster_faces.py"
    environment:
      - ENCODINGS_PATH=/app/encodings/encodings.pickle
      - FACE_DATA_PATH=/app/database
      - CLUSTERING_RESULT_PATH=/app/results
